Default: &defaults
  database: hackstarter.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: hackstarter_test.sqlite3
  <<: *defaults

Staging:
  database: hackstarter_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: hackstarter_production.sqlite3
  poolsize: 100
  <<: *defaults
